on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i --save-dev
      - name: lint
        run: |
          npm run lint
  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@master
      - run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
      - name: Make archive
        run: |
          DATE=$(date "+%Y%d%m-%H-%M")
          NAME="${REPOSITORY_NAME}_${DATE}"
          echo "FILE_NAME=${NAME}" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.FILE_NAME}}
          path: |
            ./
            !*git*
            !node_modules/*
            !package-lock.json
          if-no-files-found: error