on: push

jobs:
  build-and-upload:
    name: "Lint and Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm i --save-dev
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build

      - run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
      - name: Make archive
        run: |
          DATE=$(date "+%Y%d%m-%H-%M")
          NAME="${REPOSITORY_NAME}_${DATE}"
          echo "FILE_NAME=${NAME}" >> $GITHUB_ENV
      - name: Upload Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.FILE_NAME}}
          path: |
            ./
            !*git*
            !node_modules/*
            !package-lock.json
          if-no-files-found: error